mandatoryAccounts:
  # We recommend you do not change mandatory account names. These are used within Landing Zone Accelerator to reference the accounts from other config files.
  # The "name" value does not currently support spaces
  # The "name" value DOES NOT need to match the account name
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: <management-account>@example.com <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Root
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: <log-archive>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: <audit>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
workloadAccounts:
  # The "name" will be used to set the AWS Account name
  # The "name" value does not currently support spaces
  # The "name" value DOES NOT need to match the account name
  - name: Network-Prod
    description: Network Prod
    email: <network-prod>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Infrastructure/Infra-Prod
  - name: HIS-Dev
    description: HIS Dev
    email: <his-dev>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: HIS/HIS-Non-Prod
  - name: EIS-Prod
    description: EIS Prod
    email: <eis-prod>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: EIS/EIS-Prod